# Generated by Django 4.0.6 on 2022-08-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.BigIntegerField()),
                ('property_class', models.SmallIntegerField()),
                ('neighborhood_code', models.SmallIntegerField()),
                ('town_code', models.SmallIntegerField()),
                ('type_of_residence', models.FloatField()),
                ('apartments', models.FloatField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('census_tract', models.FloatField()),
                ('property_address', models.CharField(max_length=255)),
                ('age', models.SmallIntegerField()),
                ('neighbor_mapping', models.SmallIntegerField()),
                ('town_and_neighbor', models.IntegerField()),
                ('after_ban', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLeadInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_img', models.ImageField(upload_to='lead_img')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
