# Generated by Django 4.0.6 on 2022-08-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True)),
                ('address', models.CharField(max_length=50)),
                ('confirmed_lead', models.BooleanField(default=False)),
                ('suspected_lead', models.BooleanField(default=False)),
            ],
        ),
    ]
