# Generated by Django 4.0.6 on 2022-08-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.BigIntegerField()),
                ('est_year', models.SmallIntegerField()),
                ('pct_minority', models.FloatField()),
                ('pct_single', models.FloatField()),
                ('pct_non_english', models.FloatField()),
                ('median_hh_income', models.IntegerField()),
                ('pct_hh_below_poverty', models.FloatField()),
                ('pct_hh_with_children', models.FloatField()),
                ('hyd_year_stamped', models.SmallIntegerField()),
                ('g_label', models.FloatField()),
                ('property_class', models.SmallIntegerField()),
                ('neighbor_code', models.SmallIntegerField()),
                ('town_code', models.SmallIntegerField()),
                ('type_of_residence', models.FloatField()),
                ('prior_tax_land', models.FloatField()),
                ('prior_tax_building', models.FloatField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('census_tract', models.FloatField()),
                ('property_address', models.CharField(max_length=255)),
                ('age', models.SmallIntegerField()),
                ('neighborhood_code', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLeadInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_img', models.ImageField(upload_to='lead_img')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
