# Generated by Django 4.0.6 on 2022-08-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapinfo',
            name='suspected_lead',
            field=models.CharField(choices=[('ASSUMED NON-LEAD', 'Assumed Non-Lead'), ('UNLIKELY', 'Unlikely Lead'), ('MAYBE', 'Maybe Lead'), ('LIKELY', 'Likely Lead'), ('ASSUMED LEAD', 'Assumed Lead'), ('NON-RES', 'Non-residential'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
