# Generated by Django 4.0.6 on 2022-08-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapinfo',
            name='apartments',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='census_tract',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='property_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='type_of_residence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
