# Generated by Django 4.0.6 on 2022-08-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mapinfo_suspected_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapinfo',
            name='confirmed_lead',
        ),
        migrations.RemoveField(
            model_name='mapinfo',
            name='suspected_lead',
        ),
        migrations.AddField(
            model_name='mapinfo',
            name='lead_options',
            field=models.CharField(choices=[('CONFIRMED NON-LEAD', 'Confirmed Non-Lead'), ('ASSUMED NON-LEAD', 'Assumed Non-Lead'), ('CONFIRMED LEAD', 'Confirmed Lead'), ('ASSUMED LEAD', 'Assumed Lead'), ('NON-RES', 'Non-Residential'), ('NO INFO', 'No Information')], default='NO INFO', max_length=20),
        ),
    ]
